### ISSUE TITLE
Publish to Maven Central

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/java-app-lib#2]

**Comment by hanshenrik** [comment]
+1

**Comment by cambierr** [comment]
I published a link to a great guide here: https://github.com/TheThingsNetwork/java-app-lib/blob/api_improvements/MAVEN.md
Do not hesitate to slack me in case you need some help

**Comment by FokkeZB** [comment]
I saw, thx 😜

**Comment by FokkeZB** [comment]
JIRA ticket created: https://issues.sonatype.org/browse/OSSRH-25140

**Comment by FokkeZB** [comment]
Initial releases published to staging, waiting for sonatype

**Comment by FokkeZB** [comment]
Should be published soon. I documented at https://github.com/TheThingsNetwork/java-app-lib/wiki/Publishing-to-Maven-Central

**Comment by FokkeZB** [comment]
Done: https://oss.sonatype.org/#nexus-search;quick~TheThingsNetwork
