### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by FokkeZB** [TheThingsNetwork/java-app-lib#3]
See https://github.com/TheThingsNetwork/docs/issues/32

It should have:
- [ ] API Reference
- [ ] Quick Start (step by step building the example in the readme, including depending on the library via maven en running it)

**Comment by FokkeZB** [comment]
The API reference should be a Markdown file in the repo, just [like our CLI](https://github.com/TheThingsNetwork/ttn/tree/refactor/cmd/docs), ideally generated from JavaDoc. I'll then pull it in to the docs automatically.

**Comment by cambierr** [comment]
I came across this for the API Reference in javadoc to markdown: https://github.com/delight-im/Javadoc-to-Markdown Could you check the output format and tell me if it fit the style requirements ?

**Comment by FokkeZB** [comment]
The output is pretty good:
https://gist.github.com/FokkeZB/5ac8cf9a2001139b1a689c2a45f3545e

It might need some post-processing, but nothing a handful regex's can't solve.

**Comment by FokkeZB** [comment]
Let's just manually document like we do for Arduino:
https://github.com/TheThingsNetwork/arduino-device-lib/blob/master/API.md

I tried generating for C++ as well, but it pulls in dependencies and this way we can have full control over the output.

**Comment by FokkeZB** [comment]
Closed by #21 and https://github.com/TheThingsNetwork/docs/pull/82
